### ISSUE TITLE
Issue with build for D74048 (242590)

### ISSUE THREAD

**Issue by bader** [google/llvm-premerge-checks#120]
**Describe the bug**
I'm not sure if it's pre-merge script bug, but I see a strange failure in the logs, which probably is not related to the patch content.

```
+ cd /mnt/disks/ssd0/agent/workspace/amd64_debian_testing_clang8/build
/mnt/disks/ssd0/agent/workspace/amd64_debian_testing_clang8/llvm-premerge-checks/scripts/run_cmake.sh: line 26: cd: /mnt/disks/ssd0/agent/workspace/amd64_debian_testing_clang8/build: No such file or directory
[
```

Relevant links: https://results.llvm-merge-guard.org/amd64_debian_testing_clang8-2247/console-log.txt

**To Reproduce**
1. Submit
2. 

**Expected behavior**
No error from `cd` command.

**Screenshots**

**Comment by bader** [comment]
There are multiple reports from the bot. Here are links to the relevant reports.
https://reviews.llvm.org/D74048#1859313
https://reviews.llvm.org/D74048#1859367

**Comment by bader** [comment]
https://reviews.llvm.org/D74048#1859771 passed the problem with `cd`, but `clang-format` check proposes strange patch, which seems to just original patch. I thought it's suppose to provide a patch on top of the version submitted for review. Right?

**Comment by ChristianKuehnel** [comment]
The problem with the missing path should be resolved with 0a636404c640f10a35500b3caf54f1471b8c530c.

I'm not sure what you mean with "there are multiple reports". The bot creates one comment per build and we have one build per revision that you submit.

However the  plan is to reduce the feedback the bot gives and rely more on the Phabricator features #119 .

**Comment by bader** [comment]
Thanks what I meant is that first two reports exposes the bug, but later reports are fine.

@ChristianKuehnel, do know what is wrong with clang-format patches attached to the bot comments?

**Comment by metaflow** [comment]
I believe that were a temporary breakages introduced by me: build directory was not created (cmake failures) and applied patch was not staged (clang-format reported whole diff as "format fixes").

Thank you for noticing and reporting that! :100: Right now build should work fine.

**Comment by bader** [comment]
Cool. @metaflow, thanks for the update.
