### ISSUE TITLE
Windows agents not starting after reboot

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#129]
It looks like the Windows agents are not starting after a reboot of the windows machine. It seems that the docker service is not starting automatically even though the service is set to automatic starts.

**Comment by bader** [comment]
@ChristianKuehnel a see few issues are opened for Windows agents, so I'd like to confirm that problem I see https://reviews.llvm.org/D72857#1882573 is already tracked by one of these issue.
All log files in the [summary](https://00e9e64bacca0db1b6d0c1c48d895b0dda2f29eb4584615b3c-apidata.googleusercontent.com/download/storage/v1/b/llvm-premerge-checks/o/results%2Famd64_windows_vs2017-923%2Fsummary.html?qk=AD5uMEv1KHzerKj-xKvJlb3HZ991xfBpaNA0orVIfRiAtZayfYzO3upJCsFmNA8p-M5_rlXOljXWt8HB3vUKFeNMmb65wGNH5HVy_083JGd22v3Q_FUC00NsUgUi8-e71q3Ht4watpQiOY1l-p2_rLK1qj4D17y7f6D9holtQvQ9xiL_Fe5R993HdPcLWX1yDGONogXpxtSmqgMRhw4aspzpT4mbHXMWZwy_WOZ9r6xu1elAugcUoYG2EsrkJz86Y4-tOuVpfDKixR-nNha6YJqQlAlUPnw2aPSAN9aZDo0kL8wI3zS01LkATXvnkZNAgA_PXzNcSY-qjuEtS2dJPJPdzDp2ZgVXA0wOHHENruGhzwo6ehkxKzv7LSyBJrYhLz1Y74Ku1EqFHOlOBg3uA92UinrwkYRmR_XCFQu_SsV_m-ZIn4USXTGZ5g7dh2sOmIzA_mGTKEUExaX8CcbNbBXVWOYwd3RMg_UnapRrrbbgwGuR_55fIjo-rPlplF5RL7S9Vy0j8m57tXLiQI__mQY7O49AkyzNpKBet293molJVbx46w09T0orELucYoEBLq0cbRlKGo2StRmPF74qAcLREGmOvxMxn1HJ24SydTqI5eB0UlbJjIDJyvpey44Eek7kTrWjUvhJOGI20VOHSUT5FZ0jr_OS2unajw5tzA6_XLiXgU8kzzGsO3tXfVnAMURe6gCJ2GEvek4XP9-S5cgfUXP6r6xmfbC-lxhdFDs_e0fUvoYeLlqBl6D3KyH37OJqmymITnQ7d8kTRE81IyqI1FO-fl_n5VXW4kMklrdd67-rf5omqYy_4DAUZ1b3twddJea56iJsTTPOBMH3WVwAeNcshIKZnw) say:
```
"error":{"errors":[{"domain":"global","reason":"badLockedDomainRequest","message":"Bad Locked Domain Request"}],"code":400,"message":"Bad Locked Domain Request"}}
```
Is this already known issue or should I open a new one?

**Comment by ChristianKuehnel** [comment]
Please open a new bug. We probably need to configure full URLs in the summary.html...

**Comment by ChristianKuehnel** [comment]
this seems to be solved with starting docker service with a delay:
Services -> Docker Engine ->  Startup Type = "Automatic (Delayed Start)"
