### ISSUE TITLE
Build reported failed on Phab but summary shows success

### ISSUE THREAD

**Issue by joker-eph** [google/llvm-premerge-checks#134]
Here is the summary: https://results.llvm-merge-guard.org/amd64_debian_testing_clang8-2803/summary.html

But Phab says "Harbormaster failed remote builds in B46593: Diff 244855!" ; see here: https://reviews.llvm.org/D74683

**Comment by joker-eph** [comment]
Summary:

```
Unit tests pass. 62834 tests passed, 0 failed and 878 were skipped.
clang-tidy pass.
clang-format pass.
```

**Comment by ChristianKuehnel** [comment]
It looks like the windows build has failed: https://reviews.llvm.org/harbormaster/build/49124/
But it did not upload the results to Phabricator.
