### ISSUE TITLE
lld naming conventions flagged by clang-tidy

### ISSUE THREAD

**Issue by androm3da** [google/llvm-premerge-checks#142]
`clang-tidy` flags naming coding style problems in the monorepo but different subprojects have different coding styles.

Can we blacklist lld from the scope of these `clang-tidy` checks?

@maskray @sidneym

**Comment by joker-eph** [comment]
I believe the proper way is to configure clang-tidy in the project itself, you can take inspiration in what we did in MLIR: https://github.com/llvm/llvm-project/blob/master/mlir/.clang-tidy

**Comment by MaskRay** [comment]
https://reviews.llvm.org/D75809 will add `lld/.clang-tidy`

@joker-eph `mlir/.clang-tidy` is not ideal because it will suppress top-level `.clang-tidy` specified checks which are otherwise enabled.

```
% clang-tidy --list-checks mlir/CMakeLists.txt             
Enabled checks:
    readability-identifier-naming
```

**Comment by njames93** [comment]
There is a patch in the works that may help alleviate this https://reviews.llvm.org/D75184 however now it may be wise to just copy the root .clang-tidy and then edit the naming convention
