### ISSUE TITLE
Issue with build for D75749 (248732)

### ISSUE THREAD

**Issue by tzolnai** [google/llvm-premerge-checks#143]
**Describe the bug**
I just have a usability concern here. When I met with a pre-merge check failure for the first time, I did not find the build log easily. I saw this on the review site: 
Build 51972: pre-merge checks | summary linux · clang-tidy linux
I clicked on the "Build 51972: pre-merge checks" text which is a link and it led me to somewhere which is not the build log. It took some time to find out the actual link which shows me, what I'm interested in. I think it would be good to place the build log at the first place or make it more clear which is the build log and which is the build configuration info. The three items displayed for the pre-merge check (e. g.Build 51972: pre-merge checks, summary linux, clang-tidy linux) are not even displayed as a link (different text color and underlining) which makes hard to see there are actually more links there.
Of course, after the first time, after I've spent some time with it, now I know how to find the actual build log.

Relevant links:
https://reviews.llvm.org/D75749

**To Reproduce**
1. Check the result of a pre-merge check failure on "Diff Detail" panel

**Expected behavior**
The link placed in the description should lead to the build log in the first place. It's more important info than the build configuration. Or at least, it should be more explicit that there are more links there and which one is the build log. "summary linux" and "clang-tidy linux" strings are not really clear that they are build logs.

**Comment by metaflow** [comment]
now link to build log is added directly next to the build
