### ISSUE TITLE
Linter reports are unusably intrusive

### ISSUE THREAD

**Issue by LebedevRI** [google/llvm-premerge-checks#144]
See e.g. https://reviews.llvm.org/D75748?id=249099
The very first `Lint: Pre-merge checks` "comment" is 10+ browser pages long,
and it can't be collapsed.

**Comment by ChristianKuehnel** [comment]
@metaflow could you please take a look?

**Comment by metaflow** [comment]
Sure!

**Comment by metaflow** [comment]
now only first 10 lines will be displayed. One has to look into a report to find full diff.
