### ISSUE TITLE
Patching seems to be stripping whitespace

### ISSUE THREAD

**Issue by sam-mccall** [google/llvm-premerge-checks#147]
**Describe the bug**
The pre-merge checks seem to (sometimes?) strip trailing whitespace on modified lines, before building. This causes spurious failures when that whitespace is significant (e.g. inside a raw string literal.

---

For this diff: https://reviews.llvm.org/D75687?id=250624
The test run shows ClangdTests::Hover.PresentRulers failing: https://reviews.llvm.org/harbormaster/unit/view/23480/

Looking at the output, the failure is that the string `ExpectedMarkdown` is missing two spaces. These spaces are trailing spaces inside a raw string literal, on a line that was modified (line 1908 of HoverTests.cpp).

However in my local git workspace and in phabricator, the trailing spaces are present. So I suspect something is stripping the whitespaces when applying the patch on the buildbots.

Note that there are other similar tests in that file with significant trailing whitespace, on lines that were *not* modified (such as line 1852). Those tests pass fine, which again suggests it's the patching process that is the problem.

**Comment by ChristianKuehnel** [comment]
Will look into how we apply the patches from Phabricator. IIRC there were some issues on Windows so I fiddled with the flags a lot to get it working there. Maybe this broke something in these situations...

**Comment by ChristianKuehnel** [comment]
As we're applying the patches only on LInux (and storing the result in a git commit), we do not need to care about Windows specialties any more. So not it's a plain `git apply`...
