### ISSUE TITLE
Failure to apply the patch resulted in a green build.

### ISSUE THREAD

**Issue by hlopko** [google/llvm-premerge-checks#149]
**Describe the bug**
Failure to apply the patch resulted in a green build. After the rebase of the diff I got the failing build.

Relevant links:
Relevant build: https://reviews.llvm.org/harbormaster/build/54566/
Test log: [long link](https://00e9e64bac1fc4896eb50e6a474e3020b0fc00e013f9b40c2f-apidata.googleusercontent.com/download/storage/v1/b/llvm-premerge-checks/o/results%2Famd64_windows_vs2017-1688%2Fconsole-log.txt?qk=AD5uMEt2PSdJALRhWb8zEsMa-CveDGdmEPz9sdo0IcYJA7vQ5TS0xq2eH3h8MLnBNkhRmSs5o242SB5VDHc3BER3HFVy5QwL1f9chQ99zkMmULPKlYUfB3aWBEWN7n_D8qJXmeb4XY2YNF_7bVHrnB343ZZL9eCd6DdgtVKkkOHmYvH_56QLoPinuR9vs-pyft80muoKzs30Z2vxIrj65pbFpy3Qjn4F71N9mRzZAozTw4jyaMbPcgD7TwWete-IZ9KzFUOS_Ur_zKfCFKseU8a8UA4adWzMsY25WJ6aVt4zrlOnEH39xLRNroH5NDxnUvPAHAC4p2OBFqKtrEHhidVOW5GuT4RF53NVawS2NiiM2eN0Rdx-za0rfXRbcrrwRdplnblcsZT5sNF7YEVN3G3DVp7T4u7-Qa5t5EhEZU1o-EucpFseGk4GH4Bc1oC5qzQXZUGa2KhXwE6aElqUc2bPzt2498KpHbRA86TJfmL7h5LC5tUo58QcOr5EY8tiv3gmhY05R6ZPY8k7gtHVltP7UWyy40L4RtjKcs5fX-sAAfS3cRROPHAc4MNBQIj7TOvhLL6HOXILZHH67VaZxyOyQ3NZ5xIeM6aQcWkcFhtnXsgsCykMAeg7q9XbCtYxVHUiOTIsyeD9wYXrVyAUVMlOKQ6tyBY32Cu9TG5M7DevnTAywBXAAzONpVdQltbNMDLIpyTW6ugkP2ZAdsxR044ANDcukh5HdsUbVPg5h-2YE0vhadss4XP9z-J4-ZI5la7s0M6tM06Abbqj6NPU6GXk4DpJpiH9SiN-wtK658YLkFgfqCE9J5DTkA9AfFJF6tC0y08riH_mPzQj4ixFG0fzPGWQLPkzWr7RqZHlyZPsQOM-CTvlx0A&isca=1)
Failing build after the rebase: https://reviews.llvm.org/B49854

Relevant snippet:

```
C:\ws\workspace\amd64_windows_vs2017\llvm-project>python C:\ws\workspace\amd64_windows_vs2017/llvm-premerge-checks/scripts/phabtalk/apply_patch2.py --comment-file C:\ws\workspace\amd64_windows_vs2017/build/.phabricator-comment  --token **** --url https://reviews.llvm.org 251582 
Getting dependencies of 251582
Getting dependencies of 251572
Checking out be95744d563cf0f003d171215230affcbb2e9e9f...
ERROR checking out revision be95744d563cf0f003d171215230affcbb2e9e9f. It`s not in the repository. Using master instead.
Revision is fd7300f717c18c861e77685efe6f16f12fb63ae7
git reset, git cleanup...
Analyzing D76433
This diff depends on: D76366
  Already landed: D76366
  Will be applied: 
All depended diffs are applied
Applying diff 251582 for revision D76433...
Traceback (most recent call last):
  File "C:\ws\workspace\amd64_windows_vs2017/llvm-premerge-checks/scripts/phabtalk/apply_patch2.py", line 250, in <module>
    patcher.run()
  File "C:\ws\workspace\amd64_windows_vs2017/llvm-premerge-checks/scripts/phabtalk/apply_patch2.py", line 106, in run
    self._apply_diff(self.diff_id, revision_id)
  File "C:\ws\workspace\amd64_windows_vs2017/llvm-premerge-checks/scripts/phabtalk/apply_patch2.py", line 165, in _apply_diff
    raise Exception('Applying patch failed:\n{}'.format(proc.stdout + proc.stderr))
Exception: Applying patch failed:
error: patch failed: clang/unittests/Tooling/Syntax/TreeTest.cpp:47
error: clang/unittests/Tooling/Syntax/TreeTest.cpp: patch does not apply
```

**To Reproduce**
Run a presubmit for a diff that needs rebasing.

**Expected behavior**
Build failure, complaining about the conflict.

**Comment by hlopko** [comment]
Dup of https://github.com/google/llvm-premerge-checks/issues/141

**Comment by ChristianKuehnel** [comment]
That is indeed very strange. The Jenkins pipeline detected that `apply patch` failed, but somehow we seem to have uploaded the wrong result to Phabricator.

I just added mor log output to narrow down the problem...

**Comment by ChristianKuehnel** [comment]
Was a bug in phabtalk.py with a missing else statement

**Comment by hlopko** [comment]
Thanks for a super quick fix Christian!

**Comment by ChristianKuehnel** [comment]
Thx for raising the issue. Happy to help. 

With the basic thing in place, it's not about polishing all the rough edges to make it really useful...
