### ISSUE TITLE
clang-format-diff not found in user's PATH; not linting file.

### ISSUE THREAD

**Issue by joker-eph** [google/llvm-premerge-checks#152]
See here https://reviews.llvm.org/D77322 

![Screen Shot 2020-04-02 at 10 47 38 AM](https://user-images.githubusercontent.com/3372300/78281723-f541bd80-74cf-11ea-9ea1-8f9026b47ae3.png)

**Comment by joker-eph** [comment]
Oh this is a brand new script that landed in the monorepo two days ago, apparently it relies on something I don't have locally. 

It isn't clear to me why do I have `git clang-format` working but this script does not...

**Comment by dmpolukhin** [comment]
@joker-eph have you figured out what was wrong with your setup?
I have similar issue on all file but the message is "clang-format not found in user's PATH; not linting file." but I do have `clang-format` in my path and `git clang-format HEAD~1` works fine. Therefore I had to upload https://reviews.llvm.org/D75184 with `--nolint` to workaround this issue.

**Comment by joker-eph** [comment]
Yeah the script was relying on a clang-format-diff.py before instead of calling directly into clang-format. It has been updated to call into the clang-format-diff.py in tree. 

You can try to run `clang/tools/clang-format/clang-format-diff.py` to debug your local setup

**Comment by joker-eph** [comment]
The linter script is here FYI: https://github.com/llvm/llvm-project/blob/master/utils/arcanist/clang-format.sh

**Comment by dmpolukhin** [comment]
The problem was indeed in my PATHs and with the fact that `arc` command should be in PATHs too, in the past you were able to use full path to `arc` (it was convenient if you have incompatible arc for different projects).
