### ISSUE TITLE
Create proposal for new build infrastructure without Jenkins

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#154]
## limitations of the current Infrastructure
* users can't access Jenkins, they can't see the build status/results
* we need to serve the build status/results from another infrastructure (http sever/GCP)
* we need to maintain a bunch of services
* we can't hook up non-Google Cloud build machines

## Goal
Find a way to use off-the-shelf CI systems (e.g. Buildkite, Github Actions) with Phabricator.

## Steps
* We already have some scripts that create [git branches](https://github.com/llvm-premerge-tests/llvm-project/branches) for Phabricator Diffs.

**Comment by metaflow** [comment]
What we want: 
- (optionally) react to the calls from Phabricator
- periodically check new diffs
- run a script to setup new PR
- clean up old PR (close them?)
- (nice to have) trigger different builds depending on the content of PR
- agents: win / linux, should be easy to add public ones (e.g. not tied to the single platform)
- report results back to Phabricator
- (nice to have) query results, create statistics

I will look first onto github actions as they are closer to github and has a better integration with github features.

**Comment by metaflow** [comment]
https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources:
Each virtual machine has the same hardware resources available.
2-core CPU
7 GB of RAM memory
14 GB of SSD disk space

So machines offered by GitHub seems to be fine for toy runs only.

**Comment by metaflow** [comment]
I have read a bit about github workflow and actions. With them it's possible to implement very complex workflows with arbitrary actions. The downside is that they only seems to allow shell commands, javascript or running a docker container as an action. Not sure how restrictive is that and how easy is to develop / debug such actions. Will try to create a simple workflow of creating PRs based on @ChristianKuehnel 's script.

**Comment by metaflow** [comment]
...or maybe first check buildkite as it also has pipelines and we have a positive exp using it.

**Comment by ChristianKuehnel** [comment]
solved in #161
