### ISSUE TITLE
Documentation should say how to run each step locally 

### ISSUE THREAD

**Issue by sqkerner** [google/llvm-premerge-checks#160]
From https://github.com/google/llvm-premerge-checks/blob/master/docs/user_doc.md :

> The checks comprise of these steps:
> ...
> Run the test suite -- ninja check-all
> Run clang-format and clang-tidy on the diff.

All but the last step have a command showing how to reproduce a failure locally.  Having such a command for "Run clang-format and clang-tidy on the diff." would be helpful.

**Comment by ChristianKuehnel** [comment]
I agree this would be a good thing to have. However, we need quite some scripting and tools to reproduce the exact behaviour of the pre-merge tests. So I'm not sure if that is so easy to implement.

For the beta testers, we're already printing the CMake configuration string. 

For clang-format/tidy, [lint.sh](https://github.com/google/llvm-premerge-checks/blob/master/scripts/lint.sh) is the thing that we're running. I'm not sure if that works out of the box an a Linux machine and git commit...

**Comment by sqkerner** [comment]
Could you link to that lint script?  Seeing what it was doing allowed me to figure out that this is what I needed to do:

```
git-clang-format   HEAD
```

**Comment by ChristianKuehnel** [comment]
similar to #42

**Comment by metaflow** [comment]
Hi @sqkerner! I have added reproduction steps to the builds, e.g. https://buildkite.com/llvm-project/premerge-checks/builds/4662#d5290940-2e3d-402b-aa69-73063e7322e3 
![cMi7ZLQ6RfP](https://user-images.githubusercontent.com/254523/88176205-34368300-cc27-11ea-96ee-e01823ba98d9.png)
is that good enough?

**Comment by sqkerner** [comment]
> is that good enough?

Yes, that does make it easy to see what went wrong.
