### ISSUE TITLE
Not all already merged diffs are detected in a stacked diff

### ISSUE THREAD

**Issue by konstantinschwarz** [google/llvm-premerge-checks#181]
I created a stacked diff in https://reviews.llvm.org/D78319
The first two patches have been merged in the meantime, while I'm still working on D78319.
When updating that revision, the apply-patch script correctly detects that D78318 already landed, but still tries to apply D78316:
[2020-05-11T11:48:46.327Z]   Already landed: D78318
[2020-05-11T11:48:46.327Z]   Will be applied: D78316

This results in an unable to apply error:
[2020-05-11T11:48:46.327Z] Exception: Applying patch failed:
[2020-05-11T11:48:46.327Z] error: patch failed: llvm/lib/Target/AArch64/AArch64Subtarget.h:19
[2020-05-11T11:48:46.327Z] error: llvm/lib/Target/AArch64/AArch64Subtarget.h: patch does not apply
...

**Comment by ChristianKuehnel** [comment]
Looked into the situation:
* [build log](https://results.llvm-merge-guard.org/apply_patch-250/console-log.txt)
* base revision: [3bc95257315f1dabe6276d33c5180135b2666d17)](https://github.com/llvm/llvm-project/commit/3bc95257315f1dabe6276d33c5180135b2666d17)

D78316 was applied on April 8th, the script only scanned in the git log back as far as April 29th (1000 revisions). This is why it could not see that the Revision has landed already.

I'll change this behavior to scan the last 90 days.

**Comment by ChristianKuehnel** [comment]
@konstantinschwarz Thank you for pointing this out 👍 . My assumptions that it's enough to scan the past 1000 revision was obviously false.

The patch was applied successfully now: https://results.llvm-merge-guard.org/apply_patch-326/console-log.txt

I just triggered a new build manually. This should get you the full build results: https://reviews.llvm.org/B56404
