### ISSUE TITLE
Logs are not accessible

### ISSUE THREAD

**Issue by davidchisnall** [google/llvm-premerge-checks#187]
I am reviewing a patch that failed to build on Windows:

https://reviews.llvm.org/D80218/new/

This is surprising, given that the submitter uses Windows but I wanted to check the logs before I merged it.  The link to the build logs is:

https://storage.cloud.google.com/llvm-premerge-checks/results/amd64_windows_visualstudio-530/console-log.txt

This requires a Google Account login.  I do not have a Google Account, I do not want to have a Google Account, and at no point has it ever been raised that agreeing to Google's privacy policy should be a prerequisite for contributing to LLVM, yet I cannot commit this patch without understanding why this test is failing.

There is no reason that build logs should be private (seeing Phabricator pages without commenting on them does not require logging in), so the simplest solution would be to store the build logs somewhere publicly accessible.

**Comment by joker-eph** [comment]
Interesting, the logs are public I believe: https://00e9e64bac62275406a2e180fe1bc78f476834c59e67786dad-apidata.googleusercontent.com/download/storage/v1/b/llvm-premerge-checks/o/results%2Famd64_windows_visualstudio-530%2Fconsole-log.txt?qk=AD5uMEup9dAVQ5wCdLhY41pg1pLlPJHBinZyRgFr8V5i9BSJeAyfaY5R56Df3pIrnlsyDiERP1V9q9NCvYzGyGIkQr7GJORrAjKBI6jEBlTebegg-jVXbSwNUPwXS8rIRz1ysu7UyP0dLY2DTwFDlBWQ1muZzw7XMkMHru9lvp9c8fLQqY6cSGVmmOLGH_2N4PSDhpr-9tDOtAd78ct7ZtzFwAjPwYZlH2_FbA2keIwYevd8L2LiKOzhoBe0Jrbn3lc5c8TQtq-coAudz4PMisbOU7xgiBRHf47H-pdmld9Oer0MgX4kzkMi39IrxbuUh41hG7Ftna2kPFDr6fDjQGk8EGysDODC66ookiAEPNDKd90NfsB-NgSJChqB60LRQ3hKx_O852jRkCkhDs1Zub3NPs278ZxvTG6Vvi7UpnJCe3aosKbXxWDMR3jlS9XKHpJXjUj_LYCM3eBX-2wTdDKq0qLWs1CfMYouhaIB4U3mpzVdl6inX1zwNVYZzXBYBri2GAAUkNikVrknMOulqjL4ZKv1qWV6B4GQOBFr0YbT006AngeKxos7JWjgj-slGyhdBQeu9UcFrPbf_3_9F_hX2X2L7QUsqdd6rgxg_4Id3IOkCV66ZAOvuv0u89Fa9-gvaryOphkfkkVyR9kDG-XeZzoAJNlSi4MxPjKxK9_Kfp5jTX30lPsy3l2oSgeJpoOkdJl--zy7yQYp7p9ui5Gx4da_qcrqJXXWWa7A_sF_lz7WVDzp4Xc2kbrTcFjR6tim8O4oIHgCm-jDsbrlQUsM4zBV-D-D43F9aI4ty8efr7rAdVLuGP59kjB37bxiNKO4mSXPnWKzmzqatmjGfHRmlRENreBxwyoV-vqiFGKnqJLRpvjCQYo&isca=1

But the link in the revision is using a redirecting service which forces to log in...

The team is working on a possible migration to use BuildKite to drive these builds and handle the log management, I think this would solve this issue (example of build log: https://buildkite.com/mlir/mlir-core )

**Comment by ChristianKuehnel** [comment]
@davidchisnall, I fully agree! Thank you for raising this issue! 

These logs were configured to be public, as are those for Linux. I double checked the storage configuration and this looks like a bug somewhere in the Cloud Storage. I raised a bug there (ticket 157393846).

**Comment by ChristianKuehnel** [comment]
@davidchisnall can you please try this URL:
https://storage.googleapis.com/llvm-premerge-checks/results/amd64_windows_visualstudio-530/console-log.txt

That seems to be a different API to the same file. If that works, we'll use that URL for all future builds...

**Comment by davidchisnall** [comment]
Yup, that one works.  Thanks!
