### ISSUE TITLE
Jenkins agent failure should lead to restart 

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#2]
If build / test has failed due to e.g. machine restart Jenkins gives up and reports build as failed.
Would be nice to restart build automatically in such cases.

Initial search found [naginator](https://wiki.jenkins.io/display/JENKINS/Naginator+Plugin) plugin that should do the trick.

**Comment by ChristianKuehnel** [comment]
Just strted with the "Pipeline" feature of Jenkins. It give much more control over the build process:
https://github.com/google/llvm-premerge-checks/blob/master/Jenkins/master-pipeline/Jenkinsfile

In the docs I saw there is also a "retry" feature. Maybe that does what you want to do:
https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/#retry-retry-the-body-up-to-n-times

**Comment by metaflow** [comment]
I did some investigations:

- "retry" feature will retry a step but it will be on the same agent
- naginator plugin might do what we want but, unfortunately, it does not support pipeline build at the moment https://issues.jenkins-ci.org/browse/JENKINS-37076 .

I think that right now benefit from the pipelines is greater than restarting a job automatically - we don't have any stats on how ofter that is an issue.

Postponing for now.

**Comment by ChristianKuehnel** [comment]
won't fix because of #154
