### ISSUE TITLE
Console output is delayed on Buildkite by stdout buffering in Python

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#201]
Similar to [Jenkins](https://stackoverflow.com/questions/22826006/how-to-get-python-print-result-in-jenkins-console-output/25395339), buffered writes stdout output will be delayed in Python scripts. This makes builds look stale even if they are actually still making progress.

The Stackoverflow page lists 2 solutions: running the script with `python -u` to disable buffering or running a `sys.stdout.flush()` whenever we want the results to be shown.

**Comment by metaflow** [comment]
https://buildkite.com/llvm-project/llvm-master-build/builds/89#691474c2-f3ef-4932-9024-3fcd97414593 displays progress correctly
