### ISSUE TITLE
add checks for clang-tidy and clang-format

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#21]
### acceptance criteria:
* [x] all patched are checked with clang-tidy
* [x] all patched are checked with clang-format
* [x] the results are reported to the Phabricator page
* [x] the checks only consider the modified lines (using clang-format-diff.py / clang-tidy-diff.py)

**Comment by metaflow** [comment]
Recommended way to check for clang-format fixes is https://llvm.org/docs/GettingStarted.html#sending-patches

if it's not installed we can run `clang/tools/clang-format/git-clang-format --diff` in a directory with applied patch

**Comment by metaflow** [comment]
to run clang-tidy:

`git diff -U0 | clang-tidy-diff-8.py -p1 -clang-tidy-binary=clang-tidy-8`

should do the trick given that we copied `compile-commands.json` and the sources in question were involved in compile commands (looks like we have to enable other projects in cmake to make sure that we will compile diff).

**Comment by ChristianKuehnel** [comment]
Phabricator supports displaying "lint results" (section Lint results):
https://secure.phabricator.com/conduit/method/harbormaster.sendmessage/

I have no idea what the results looks like or on how to convert the clangtidy output to this format.

If you want to give it a shot, you can extend/rewrite/duplicate/... the script:
https://github.com/google/llvm-premerge-checks/blob/master/scripts/phabtalk/phabtalk.py

Right now the script is a quick hack to report the test results and add a comment with a short summary. This is what I needed for the compile & test scenarios.

**Comment by metaflow** [comment]
@ChristianKuehnel currently this reports look like: https://reviews.llvm.org/D71594

**Comment by metaflow** [comment]
Windows build will be addressed separately.
