### ISSUE TITLE
clang-format not found in user's PATH

### ISSUE THREAD

**Issue by AaronBallman** [google/llvm-premerge-checks#227]
Here's an example of a review where clang-format appears to not be found: https://reviews.llvm.org/D83717

(In case the behavior changes out from under that link, I'm also attaching a screenshot.)
![Capture](https://user-images.githubusercontent.com/4587626/89408111-e96c3f00-d6ed-11ea-8f1d-73a3d7a57a3d.PNG)

This kind of diagnostic is helpful to admins who may need to change the change configuration or install a tool, but isn't very helpful to users doing code reviews. Perhaps these diagnostics should not be shown to the user but should instead generate an email to llvm-admin or someone else to notify them of the configuration issue?

**Comment by metaflow** [comment]
@AaronBallman It looks like this lint message is produced by something other than pre-merge checks. Normaly they have "Lint: Pre-merge checks" title, e.g. tidy warnings in https://reviews.llvm.org/D83717?id=277588 . Buildkite build https://buildkite.com/llvm-project/premerge-checks/builds/6077#38d7865b-4e50-4f8c-84d9-085e45d90010 also seems to be happy about the diff.
