### ISSUE TITLE
Warning "invalid case style for variable" on lamda function define.

### ISSUE THREAD

**Issue by diggerlin** [google/llvm-premerge-checks#228]
const auto getExternalFunctionEntryPointSymbol = [&](StringRef SymName) {
        auto &Context = DAG.getMachineFunction().getMMI().getContext();
        MCSectionXCOFF *Sec = Context.getXCOFFSection(
            (Twine(".") + Twine(SymName)).str(), XCOFF::XMC_PR, XCOFF::XTY_ER,
            SectionKind::getMetadata());
        return Sec->getQualNameSymbol();
      };

      SymName = getExternalFunctionEntryPointSymbol(SymName)->getName().data();

I got a warning as 
clang-tidy: warning: invalid case style for variable 'getFunctionEntryPointQualNameSymbol' [readability-identifier-naming]
not useful

I think it looks as getExternalFunctionEntryPointSymbol  viable, and it should ask to name as
GetExternalFunctionEntryPointSymbol , actually it is a function. I think getExternalFunctionEntryPointSymbol is correct.

**Comment by ChristianKuehnel** [comment]
Not sure how to address this issue in pre-merge testing.
I guess this is a bug in clang-tidy?

**Comment by metaflow** [comment]
@diggerlin it seems that issue is related to clang-tidy tool, not pre-merge checks that runs it. Please reopen this issue if that is not the case.
P.S. Please attach links to phabricator review / build as they help to investigate issues.
