### ISSUE TITLE
Check if we should limits the targets we're building

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#237]
Hint from @kwk :
Check which targets are actually being built. Not setting `-DLLVM_TARGETS_TO_BUILD=X86` might cause all of them to be built.

`CMakeCache.txt` says `LLVM_TARGETS_TO_BUILD:STRING=all`

And the cmake log output contains:
```
-- Targeting AArch64
-- Targeting AMDGPU
-- Targeting ARM
-- Targeting AVR
-- Targeting BPF
-- Targeting Hexagon
-- Targeting Lanai
-- Targeting Mips
-- Targeting MSP430
-- Targeting NVPTX
-- Targeting PowerPC
-- Targeting RISCV
-- Targeting Sparc
-- Targeting SystemZ
-- Targeting WebAssembly
-- Targeting X86
-- Targeting XCore
```

Maybe we could save some build time by restricting the targets to X86...

**Comment by metaflow** [comment]
Will try that

**Comment by joker-eph** [comment]
If you build only with X86 you won't cover the other targets though?

**Comment by metaflow** [comment]
I have tried to run with -DLLVM_TARGETS_TO_BUILD=X86 https://buildkite.com/llvm-project/llvm-master-build/builds/930, with all: https://buildkite.com/llvm-project/llvm-master-build/builds/931 
So duration Linux changed from 36 to 30m (20%) and Windows from 62m to 54m (13%) for non cached build. Note that this is 1. single run 2. non cached build.

**Comment by ChristianKuehnel** [comment]
> If you build only with X86 you won't cover the other targets though?

Do we have any evidence that building more targets finds more bugs? 
Or the other way round: Do we have evidence that a significant amount of bugs only affect a subset of the targets and can be caught this way?

If not I would go for a faster build.

**Comment by metaflow** [comment]
For partially cached build on windows: https://buildkite.com/llvm-project/llvm-master-build/builds/943, 42m to https://buildkite.com/llvm-project/llvm-master-build/builds/946, 35.5m (-15%). That is consistent with the result above.

As for covering other platforms: it would be nice if there were some heuristic to detect if change is potentially non-cross platform. Also, we don't coverall configurations anyway (asan etc.).

I would suggest to set x86 target for pre-merge checks and leave all targets enabled for release / master tests. What do you think?

**Comment by joker-eph** [comment]
> Or the other way round: Do we have evidence that a significant amount of bugs only affect a subset of the targets and can be caught this way?

All the tests [here](https://github.com/llvm/llvm-project/tree/master/llvm/test/CodeGen) are exercising code in the backend.

I'm not sure I understand your view here: disabling a feature by building less code always mean faster build, but also means that the code your disabling is not tested. But this is a general property though: if we disable `lld` we get faster builds/tests, and `lld` does not contribute to finding a single bug for my patches (mostly MLIR), and vice-versa: for the `lld` folks we don't need to build MLIR, flang, and clang.

So for the targets it is a choice on what you try to test: folks working on the ARM64 backend won't get any of their code tested at all for example if you don't configure it in.

**Comment by joker-eph** [comment]
Oh an there are tests and build target we build in MLIR only if a backend is configured (we have passes that require NVPTX and AMDGPU right now), for example here: https://github.com/llvm/llvm-project/blob/master/mlir/CMakeLists.txt#L36

**Comment by metaflow** [comment]
Yea, I agree that it's better to test more unless we have a good idea of affected projects / architectures and can safely exclude some.
