### ISSUE TITLE
Scale compute power

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#24]
### acceptance criteria
* [x] All new/changed patches are checked within 2h.
* [x] We benchmarked the tests on "C" type machines to see if that's faster.
* [x] We have benchmarks for 16, 32 and 64 cores for: 
  * clean build
  * cached build
  * ninja check
  * ninja check-all

**Comment by ChristianKuehnel** [comment]
setting up VM for testing:
```bash
sudo apt-get update
sudo apt-get install -y --no-install-recommends cmake ninja-build git ca-certificates clang-7 lld-7  clang ccache python python3 build-essential python-psutil arcanist zip wget python3-pip python3-setuptools
git clone --depth=1 https://github.com/llvm/llvm-project.git
cd llvm-project
git clone https://github.com/google/llvm-premerge-checks.git
mkdir build
cd build
export CC=clang-7
export CXX=clang++-7
export LD=LLD
export CCACHE_PATH=~/ccache
mkdir -p ${CCACHE_PATH}
cmake -GNinja ../llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_LLD=ON  -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;libcxx;libcxxabi;lld" 	-DLLVM_CCACHE_BUILD=ON -DLLVM_CCACHE_DIR="${CCACHE_PATH}" -DLLVM_CCACHE_MAXSIZE=20G     -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_CXX_FLAGS=-gmlt     -DLLVM_LIT_ARGS="-v --xunit-xml-output ${WORKSPACE}/build/test-results.xml"

# clean build
time ninja all
# incremental build
time ninja all
```

**Comment by ChristianKuehnel** [comment]
results: https://docs.google.com/spreadsheets/d/1ArXlUQYUbdumUXQakWKSbeo1ttMRP4QcoiAf_7-fB3M/

**Comment by davezarzycki** [comment]
Testing is sublinear because of [Amdahl's Law](https://en.wikipedia.org/wiki/Amdahl's_law). In short, as more cores are added, the time to complete the test suite equals the time to complete the longest test. Adding more cores means fixing slow tests or relegating them to a bot that only tests "long tests" (Swift has this development model).

**Comment by joker-eph** [comment]
> In short, as more cores are added, the time to complete the test suite equals the time to complete the longest test. 

This applies equally to the building phase though right? (which suffers from the link being a bottleneck frequently)

**Comment by davezarzycki** [comment]
Yup. That being said, developers are more motivated to fix slow compiles or links than slow tests.

**Comment by davezarzycki** [comment]
For example:
d488daa0329c6d6edac929687fa842f759375c1a
d15f31936a5987a06066a2d49fba388c69a027eb
