### ISSUE TITLE
Migrate off `llvm-merge-guard.org` domain

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#242]
Right now we have our own domain for the proxy, only hosting the proxy service: llvm-merge-guard.org
This is owned right now by @ChristianKuehnel . Previously we also had the results and Jenkins on that domain. Our k8s cluster has a static IP address.

Options:
1. Since we're only hosting the proxy there, we do not need a DNS entry. We could just register the IP in Phabricator as this is the only place where we need it. And this can be updated by any Phabricator admin.
2. We could also discuss with the LLVM foundation to get a subdomain from them. E.g. premergeproxy.llvm.org. I guess setting/updating the IP will require support from the ops team.

So right now I have a slight tendency towards 1. as long as we don't need to host any other services

@metaflow what do you think?

**Comment by metaflow** [comment]
Yes, I think (1.) makes sense. Will try to fix this during this week so we don't have to continue the domain name

**Comment by ChristianKuehnel** [comment]
Awesome, thx. So I cancelled the renewal and the domain will expire on Oct 4, 2020.
