### ISSUE TITLE
buildkite build diff-checks 16099 (Read a non-existing source file)

### ISSUE THREAD

**Issue by dougpuob** [google/llvm-premerge-checks#259]
**Describe the bug**
My commit for `clang-tidy` is been reviewing, I update my change via Phabricator Arcanist with `arc diff master --update D86671` command, then build machines will be triggered on buildkite.com. Recently it always failed at `scripts/apply_patch.sh`, the log showed it was trying to read a non-existing source file (error: clang-tools-extra/test/clang-tidy/checkers/readability-identifier-naming-hungarian-notation.cpp: No such file or directory). 

What I did to the file.
First, I renamed the file, it failed on build. The log showed it reads the old file name.
Second, I renamed it back, but it still FAILED. The file is there but the log showed `No such file or directory`, it confuses me.

**Relevant links:**
[error: clang-tools-extra/test/clang-tidy/checkers/readability-identifier-naming-hungarian-notation.cpp: No such file or directory](https://buildkite.com/llvm-project/diff-checks/builds/16099#df25eaf3-685b-44ec-beac-d4893e51efd8/17-51)

**To Reproduce**
1. `arc diff master --update D86671`
2. Go to `https://reviews.llvm.org/D86671`, there is a link near "Build Status" in "Diff Detail" frame.
3. Click the link to see the build log file on buildkite.com.

**Expected behavior**
 I wish it passed on build machine, like the "Passed Case" screenshot.

**Screenshots**

- **Passed Case (https://buildkite.com/llvm-project/premerge-checks/builds/10126)**    
    ![Passed Case](https://user-images.githubusercontent.com/3453968/96820312-4909f900-1458-11eb-8f3b-3b756fc5ddb6.png)

- **Failed Case (https://buildkite.com/llvm-project/diff-checks/builds/16099)**    
    ![image](https://user-images.githubusercontent.com/3453968/96820451-98e8c000-1458-11eb-8141-fdadca1db564.png)

- **Error Log (https://buildkite.com/llvm-project/diff-checks/builds/16099#df25eaf3-685b-44ec-beac-d4893e51efd8/17-51)**    
    ![image](https://user-images.githubusercontent.com/3453968/96821974-9340a980-145b-11eb-86e8-16b9a3dc2db9.png)

**Comment by metaflow** [comment]
Thank you for the report @dougpuob  I will take a look

**Comment by dougpuob** [comment]
> Thank you for the report @dougpuob I will take a look

Hi @metaflow,
Thank you for the reply, the issue is similar to https://github.com/google/llvm-premerge-checks/issues/203. Let me know if I can do something for it.

**Comment by metaflow** [comment]
@dougpuob  I have looked into this problem a bit. The issue is definitely caused by multiple local commits. Now I am trying to wrap my head around applying multiple diffs from the same revision. It seems that ones that have identical "base" revision contains cumulative diffs and what we should try:
1. among all diffs to the revision find latest that is based on revision in upstream. Assume that all non-existent commits are local and based on top of each other.
2. Filter out all diffs that are based on the same hash
3. apply diffs that are left.

Unfortunately I didn't manage to find any relevant documentation in conduit API or the internet :globe_with_meridians: and come to this after some experiments. I will ask around if anyone knows better.

**Comment by dougpuob** [comment]
@metaflow I found a way making it works. Diff all my changes then apply them to a new branch(latest trunk), then `arc diff master --update D86671`. Thank you for your information.

You mentioned "caused by multiple local commits", do you mean always upload a single diff to Phabricator(rebase before arc diff)?

**Comment by metaflow** [comment]
@dougpuob great! I figured out (just recently) that phabricator diff might contain an arbitrary patch :open_mouth: 
I am planning to add a message like this https://buildkite.com/llvm-project/diff-checks/builds/17373 to the build. Do you think that will be helpful?

**Comment by metaflow** [comment]
@dougpuob 

> You mentioned "caused by multiple local commits", do you mean always upload a single diff to Phabricator(rebase before arc diff)?

I have reworded this a little to "The patch may not apply if it includes only the most recent of multiple local commits." but idea is the same: if one uploads patch against a local commit there is a chance that patch (or something down the line like compilation) may fail.
On the other hand stacked revisions should work as we can retrieve this information from Phabricator.

**Comment by metaflow** [comment]
@dougpuob please close this if you think it's resolved.

**Comment by dougpuob** [comment]
> @dougpuob great! I figured out (just recently) that phabricator diff might contain an arbitrary patch 😮
> I am planning to add a message like this https://buildkite.com/llvm-project/diff-checks/builds/17373 to the build. Do you think that will be helpful?

@metaflow Looks good! The error message and the hint are important to people first time encounter this issue. Thank you for the great help.
