### ISSUE TITLE
Build is not triggered if diff repository is not set

### ISSUE THREAD

**Issue by metaflow** [google/llvm-premerge-checks#263]
For example https://reviews.llvm.org/D90930?id=305761
We might need to figure out why that happens an check how many diffs are MIA

**Comment by poelmanc** [comment]
This just bit me too, e.g. https://reviews.llvm.org/D68682?id=321451. I believed the Repository field was supposed to be left blank per the LLVM Phabricator instructions at https://llvm.org/docs/Phabricator.html:
> Leave this first Repository field blank. (We’ll fill in the Repository later, when sending the review.)
> ...
> Leave the Repository field blank. (We previously filled out the Repository for the review request.)

**Comment by metaflow** [comment]
I have updated herald rule to trigger check if repository does not match any other known repo:
> Repository is not any of rZORG LLVM Github Zorg, rW llvm-www, rLNT LNT, rT test-suite
so now it should trigger on unset repository as well

**Comment by metaflow** [comment]
here is an example of build triggered by a revision w/ no repository set https://reviews.llvm.org/D97357?id=325980

**Comment by ldionne** [comment]
Nice, thanks for fixing this. It's been a source of churn in libc++ - glad to see it's fixed.
