### ISSUE TITLE
All pre-merge tests started failing

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#270]
**Describe the bug**
creating patches fails with this error message:
https://buildkite.com/llvm-project/diff-checks/builds/22635#06810434-8128-40f6-9ba5-ccf62cf0cbe1
````
INFO    Backing off reset_repository(...) for 2.6s (git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
--
  | cmdline: git push origin main
  | stderr: 'ERROR: You must verify your email address.
  | See https://github.com/settings/emails.
```

**Comment by ChristianKuehnel** [comment]
Seems to be some account issue: I can't log in to the bot's github account, because it wants to send me an email code to the associated gmail account. And the password for the gmail account does not work :(

**Comment by ChristianKuehnel** [comment]
Found the right password and confirmed the email address for the github account.

**Comment by metaflow** [comment]
Thank you for looking into that @ChristianKuehnel !
