### ISSUE TITLE
Enable flang on Windows

### ISSUE THREAD

**Issue by MehdiChinoune** [google/llvm-premerge-checks#287]
**Describe the bug**
Flang is disabled on WIndows. The developers keep ignoring (breaking building on) Windows because it is always reporting success.

**Expected behavior**
Flang project can be enabled now on Windows.

**Comment by metaflow** [comment]
I will try to run flang now. Previously it was failing on every build.

**Comment by MehdiChinoune** [comment]
> I will try to run flang now. Previously it was failing on every build.

Pending Fix https://reviews.llvm.org/D96069

**Comment by metaflow** [comment]
@MehdiChinoune Great! ./flang/README.md also tells that "The code does not compile with Windows..." Is that outdated?

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune Great! ./flang/README.md also tells that "The code does not compile with Windows..." Is that outdated?

Yes, since no one care about it.
Meinersbur (Michael Kruse) fixed all the bugs related to MSVC, but since the buildbot exclude flang, they introduced new ones.

**Comment by metaflow** [comment]
@MehdiChinoune could you please ping me here when your fix will land? (I have subscribed to diff but don't monitor it notifications closely)

**Comment by MehdiChinoune** [comment]
@metaflow
The fix has landed, building the source succeed but testing failed because many of their tests are written is Shell scripts.
See: https://bugs.llvm.org/show_bug.cgi?id=49985

**Comment by MehdiChinoune** [comment]
They started working on a new buildbot "flang-x86_64-windows"
http://meinersbur.de:8011/#/builders/146

**Comment by metaflow** [comment]
@MehdiChinoune is flang still broken on windows? How is the buildbot going to help with the shell script tests?

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune is flang still broken on windows? How is the buildbot going to help with the shell script tests?

Since they are working on a buildbot l, they will fix those issues by themselves.

**Comment by MehdiChinoune** [comment]
I think you can enable flang. They fixed the tests.

**Comment by metaflow** [comment]
thank you for the update @MehdiChinoune ! I will try to rerun build with flang

**Comment by metaflow** [comment]
@MehdiChinoune I see in https://buildkite.com/llvm-project/llvm-main/builds/2857#e1f0fb2f-3791-499d-8832-b17d4a40d6b4 that Semantics/unpack.f90 is still failing, do you know by any chance why?

**Comment by MehdiChinoune** [comment]
It was fixed yesterday.
https://github.com/llvm/llvm-project/commit/5d933c0b0c741767f2af8218d55581557903a254

**Comment by metaflow** [comment]
great! I will rerun the tests for a newer revisions then. Thank you!

**Comment by metaflow** [comment]
Thank you for following this through @MehdiChinoune, much appreciated! :+1:
