### ISSUE TITLE
Reduce the latency for completing diff-checks and other infrastructure related tasks

### ISSUE THREAD

**Issue by ldionne** [google/llvm-premerge-checks#292]
Currently, jobs that launch the actual CI pipelines are targeting agents tagged with `queue=linux`. However, those agents are the same ones that run the actual compute intensive CI. As a result, it often happens that a pipeline gets stuck in the `diff-checks` pipeline waiting for an agent to perform those fairly trivial steps. This is not a problem when the actual CI pipeline is targeting agents with `queue=linux` (since there would be no agents to perform the actual CI build anyway), however it introduces needless latency when the real CI pipeline uses different agents.

For example, the libc++ testing pipeline uses its own agents to perform compute intensive jobs. When we create a Phabricator review, we'd like it to start immediately. Right now, it often gets stuck waiting for an agent to perform the `diff-checks` pipeline, and when that's done, we're off to the races running on our own agents. When the `queue=linux` agents are under heavy load, this can increase the latency for getting CI results by up to 2-3x.

It would be nice to create one or two special agents with a tag like `queue=buildkite-infrastructure`, and have the trivial infra jobs target those agents instead. Those agents could even run on machines that already run other CI tasks, since their computational requirement is trivial.

**Comment by metaflow** [comment]
Yes that makes sense! I will add a couple of such machines.

**Comment by metaflow** [comment]
Probably on Monday as I don't want to leave it over the weekend.

**Comment by ldionne** [comment]
Nice, thanks for the quick reply! Let me know if I can help in any way. It looks like we have a mix of infrastructure jobs defined in BuildKite itself and in scripts like `scripts/pipeline_create_branch.py`, so we'll want to update all those jobs to trigger the new queue.

**Comment by ldionne** [comment]
This is awesome, thanks a lot for solving this issue quickly!

**Comment by metaflow** [comment]
Glad to help!

**Comment by mstorsjo** [comment]
Awesome, this is very welcome!

I noticed that the "buildkite-agent pipeline upload libcxx/utils/ci/buildkite-pipeline.yml" step still has to wait for some time (it just waited 19 minutes in one run), does that need some similar adjustment?

**Comment by metaflow** [comment]
Yes, the "init" step of libcxx pipeline was using "libcxx-builders" queue. I have updated it to use "service" as well.

**Comment by mstorsjo** [comment]
> Yes, the "init" step of libcxx pipeline was using "libcxx-builders" queue. I have updated it to use "service" as well.

Oh, fantastic! Thanks!
