### ISSUE TITLE
Disable misc-no-recursion

### ISSUE THREAD

**Issue by dwblaikie** [google/llvm-premerge-checks#308]
**Describe the bug**
Pre-merge checks flagged a recursive function (misc-no-recursion)

**To Reproduce**
https://reviews.llvm.org/D102581 - line 448

**Expected behavior**
Don't flag recursion as being problematic - the specific cases cited in the clang-tidy check don't look like they apply to the LLVM codebase. Recursive descent parsers and other algorithms are commonplace in the LLVM project.

**Comment by ChristianKuehnel** [comment]
Hi @dwblaikie,

Well this is nothing pre-merge specific. IIRC pre-merge testing is just using the clang-tidy configuration in the git repo. So you probably want to modify the `.clang-tidy` file there. Either in the root folder or in some of the sub-folders, depending on the scope you want to modify.

**Comment by dwblaikie** [comment]
Ah, thanks for explaining.

Seems a few subprojects had already disabled this check, but we haven't been using inherited/centralized configs. So I've sent out https://reviews.llvm.org/D103842 to use inheritance while maintaining the current checks - after that I'll draw the -misc-no-recursion down into the root config.

That said - is "misc-*" an advisable thing to do? If it's full of quirky stylistic choices like "no recursion", maybe it shouldn't be used, generally speaking & projects should more carefully opt in to whatever checks they want from there?

**Comment by dwblaikie** [comment]
looked at the list and there are few enough misc-* warnings I'm not too fussed about this. I manually inspected the description of each one and they look plausible enough except for the ones we're already disabling (public members in classes and no recursion).

Thanks for the help, all!
