### ISSUE TITLE
Feature request: Allow patch author to restart the build

### ISSUE THREAD

**Issue by whisperity** [google/llvm-premerge-checks#316]
After removing the parent revision that caused the problems I reported in #315, I tried on Phabricator to re-run the build in the new state (i.e. without letting the CI to try applying the parent patches and failing). However, because I do not have the _"Can Edit"_ permission, I couldn't restart the build manually, only by uploading the same diff again to trigger it.

The author of the patch should be able to re-run the build in case the build is only broken because of issues with the environment (e.g. `main` was broken but now is fixed so a new merge should go, or my case with the parents breaking, etc.), not issues with the patch itself. This would help not create noise with updated diffs that don't actually change anything.

![You do not have permission to edit this object. Users with the "Can Edit" capability: Administrators can take this action. You must have edit permission on this build plan to pause, abort, resume, or restart it.You must have edit permission on this build plan to run it manually.](https://user-images.githubusercontent.com/1969470/123122625-78895f00-d446-11eb-9405-727deba2e562.png)

**Comment by joker-eph** [comment]
I just changed this, you should be able to manually trigger it now.

**Comment by whisperity** [comment]
@joker-eph Thank you very much, the rerunning worked!
