### ISSUE TITLE
Disable libarcher tests on Debian

### ISSUE THREAD

**Issue by AaronBallman** [google/llvm-premerge-checks#323]
Can we please disable libarcher tests on Debian? They routinely fail to the point that it's hard to trust CI pipeline results because we need to continually remember that these are unrelated failures.
```
Failed Tests (17):
--
  | libarcher :: critical/critical.c
  | libarcher :: parallel/parallel-firstprivate.c
  | libarcher :: races/critical-unrelated.c
  | libarcher :: races/lock-nested-unrelated.c
  | libarcher :: races/lock-unrelated.c
  | libarcher :: races/parallel-simple.c
  | libarcher :: races/task-dependency.c
  | libarcher :: races/task-taskgroup-unrelated.c
  | libarcher :: races/task-taskwait-nested.c
  | libarcher :: races/task-two.c
  | libarcher :: reduction/parallel-reduction-nowait.c
  | libarcher :: reduction/parallel-reduction.c
  | libarcher :: task/task-create.c
  | libarcher :: task/task-taskgroup.c
  | libarcher :: task/task-taskwait-nested.c
  | libarcher :: task/task_early_fulfill.c
  | libarcher :: task/task_late_fulfill.c
```
(For reference, this has come up in the following randomly-selected reviews: https://reviews.llvm.org/D102343, https://reviews.llvm.org/D106302, https://reviews.llvm.org/D105951, https://reviews.llvm.org/D102728, and basically every other review I've seen in the past few months.)

Thanks!

**Comment by metaflow** [comment]
@AaronBallman do you know by any chance it's possible to disable test with cmake / ninja args? Also, maybe we should fix those tests?

**Comment by AaronBallman** [comment]
@metaflow -- I have no idea if they can be disabled from cmake or ninja arguments (it took me a while to even figure out where to go to ask for them to be disabled; they're not in the llvm project tree that I've found). Fixing the tests would probably be a good idea though, if someone knows how to do that.

**Comment by joker-eph** [comment]
Seems to be controlled by LIBOMP_OMPT_SUPPORT : https://github.com/llvm/llvm-project/blob/main/openmp/tools/archer/CMakeLists.txt#L11

**Comment by AaronBallman** [comment]
Thank you! I can confirm that this seems to be resolved now, so closing the report.

**Comment by metaflow** [comment]
then I will re-enable openmp back
