### ISSUE TITLE
Pipeline failure when changes cannot be mapped to a project

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/llvm-premerge-checks#325]
**Describe the bug**
Pipeline failure when changes cannot be mapped to a project
Relevant links: https://buildkite.com/llvm-project/premerge-checks/builds/49068#1c2315ad-dc7b-41a5-bfda-57316dece5cd

**To Reproduce**
1. Send patch touching utils/bazel/zlib.bzl
2. Pre-merge checks fail

**Expected behavior**
Pre-merge checks don't fail

**Details**
This is the failure

```
INFO    Files modified by this patch:
--
  | utils/bazel/zlib.bzl
  | WARNING Could not map file to project: utils/bazel/zlib.bzl
  | INFO    Projects directly modified by this patch:
  |  
  | WARNING There were changes that could not be mapped to a project. Checking everything
  | INFO    modified projects: ['clang', 'clang-tools-extra', 'compiler-rt', 'debuginfo-tests', 'flang', 'libc', 'libclc', 'libcxx', 'libcxxabi', 'libunwind', 'lld', 'lldb', 'mlir', 'openmp', 'parallel-libs', 'polly', 'pstl', 'llvm']
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/llvm-premerge-checks/scripts/pipeline_premerge.py", line 56, in <module>
  | affected_projects = cp.get_affected_projects(modified_projects)
  | File "/var/lib/buildkite-agent/builds/llvm-premerge-checks/scripts/choose_projects.py", line 163, in get_affected_projects
  | logging.info(f'added {affected_projects - changed_projects} projects as they are affected')
  | TypeError: unsupported operand type(s) for -: 'set' and 'list'
```

I think the issue is that at https://github.com/google/llvm-premerge-checks/blob/75ca275b109e53cc268c8ada60970e780a320fcd/scripts/pipeline_premerge.py#L53 `modified_projects` gets set to `all_projects` which is a list and then is passed to `get_affected_projects` which expects a set.

Longer-term it would be nice to not build all the unrelated pre-merge check on changes to utils, but this codepath should also work.

**Comment by metaflow** [comment]
I have restarted the build in https://buildkite.com/llvm-project/premerge-checks/builds/49068#65f3b557-2775-494d-a577-0ce0dda2a457 and it passed the "setup" stage.
