### ISSUE TITLE
Very long wait times for Windows agents

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/llvm-premerge-checks#336]
https://buildkite.com/llvm-project/premerge-checks/builds/50083 has been waiting for a windows agent for almost 2 hours. I know there are some longer-term plans to improve the situation, like #115 and #70, but in the meantime, could we spin up a few more windows agents?

**Comment by metaflow** [comment]
I have added one machine and will add one more a bit later. According to my queue simulation that should significantly drop queue time (currently we have 8 and I will increase to 10, y axis is 95 percentile of queue time)
![index](https://user-images.githubusercontent.com/254523/127526993-ea2f80ec-d6b6-4385-a464-bba9edb62f24.png)

**Comment by metaflow** [comment]
wait times seems to better 
![image](https://user-images.githubusercontent.com/254523/129056774-dbb978e0-3bf5-47f6-aae8-ea7a797116d1.png)
I have also confirmed with a new simulation that it better for us to have smaller number of 30 CPU machines that larger pool of 16CPU ones:
- 7 x 30 CPU should give ~3527s 95 percentile total time (queue time + run time)
- 14 x 16 CPU -> 5920s
according to current stats.
