### ISSUE TITLE
release/ branches are not synced into project fork

### ISSUE THREAD

**Issue by metaflow** [google/llvm-premerge-checks#337]
e.g. https://github.com/llvm-premerge-tests/llvm-project.git does not have "release/13.x"

**Comment by ChristianKuehnel** [comment]
AFAIK we only push the patches for pre-merge testing.

I'm not aware of any Github feature for automatic updates for forks. I suppose you need some Github Action (or any other build job) for that...

What is the use case for having releases in the fork? Why not use them from the original repository?

**Comment by metaflow** [comment]
> What is the use case for having releases in the fork? Why not use them from the original repository?
libcxx CI is looking at fork to run premerge checks. But to run release branch testing we need the branch to be synced too.
