### ISSUE TITLE
Look at other tools

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#35]
### acceptance criteria
* [ ] we had a look at alternative tools to run the infrastructure
* [ ] decide if it makes sense to switch

### candidates
* https://chromium.googlesource.com/infra/infra/+/master/doc/users/services/about_luci.md
* Buildkite
* we build our own, custom build scheduler
* Github actions
* cirrus-ci.org
* https://circleci.com
* https://concourse-ci.org/
* Travis CI
* ...

**Comment by ChristianKuehnel** [comment]
# buildkite
As I had trouble with Windows on k8s, I did a quick test with [buildkite](https://buildkite.com/) with a windows agent.

Here's my summary so far:
* General
  * buildkite is hosted in the cloud, you do not need to take care of anything there. That takes a lot of work off our shoulders.
  * It's free for OSS projects.
  * You must bring your build agents and you obviously need to maintain these yourself. So that's somewhat similar to our buildbots.
* setting up Windows agent
  * As usual: install all the tools you need to build.
  * Then install their client and run it with your token.
  * Really straight-forward
  * Works nicely with a Windows docker image.
* not yet tested:
  * integration with Phabricator
  * integration with Github pull requests (if we ever want to do that)

**Comment by joker-eph** [comment]
> * not yet tested:
>   * integration with Github pull requests (if we ever want to do that)

We use it in MLIR and I think it works just as you would expect there.

**Comment by ChristianKuehnel** [comment]
I talked to the bazel team, they are using buildkite and they are very happy with that solution.

**Comment by ChristianKuehnel** [comment]
Set up buildkite jobs for the release branch: https://buildkite.com/llvm-project

**Comment by ChristianKuehnel** [comment]
to be folluped up on in #154
