### ISSUE TITLE
buildkite build diff-checks 65057: patch application failed 

### ISSUE THREAD

**Issue by xgupta** [google/llvm-premerge-checks#351]
**Describe the bug**
On local system patch application is successful while on buildbot it is failing from some time.
Relevant links: https://reviews.llvm.org/D110309

**To Reproduce**
1. click on this link https://buildkite.com/llvm-project/diff-checks/builds/65057#2e3c081f-a848-4c0d-becf-ef677898c4ef
2. :bk-status-failed: Failed to apply 1_374449.patch. No testing is possible because we couldn't apply the patch.

**Expected behavior**
patch should be cleanly apply and buildbot start building the main+patch.

**Screenshots**
![patch-application](https://user-images.githubusercontent.com/72094336/134495346-925d31e9-4ecc-405d-90a9-308891498303.png)

**Comment by joker-eph** [comment]
Did you create your patch with `arc` or uploading it through the web?

Also Teresa fixed the same thing yesterday, it may be that this is where the conflict came from: https://reviews.llvm.org/D110309#3018173

**Comment by xgupta** [comment]
Yes correct, sorry for the noise
