### ISSUE TITLE
buildkite build premerge-checks 58009

### ISSUE THREAD

**Issue by carlosgalvezp** [google/llvm-premerge-checks#353]
It seems there's a bug for the Windows build, unrelated to my patch

```
ninja: error: unknown target 'check-libc', did you mean 'check-lit'
```
https://buildkite.com/llvm-project/premerge-checks/builds/58009#40138b8b-ecaa-4a7b-8894-cc6f5dc942fb

**Comment by joker-eph** [comment]
Can you link the patch as well?

**Comment by joker-eph** [comment]
Ah found it: https://reviews.llvm.org/D110493?id=375088

**Comment by joker-eph** [comment]
Libc depends on clang-tools-extra, so revisions that touching clang-tools-extra runs the libc tests. That seems to work as intended.

The strange part is that the check-libc target is somehow not present on Windows, and I can't figure out why?

**Comment by carlosgalvezp** [comment]
Thanks a lot for looking into this! I really wish I could help, but it's my very first patch to LLVM so I'm quite new to all this :) Looking at previous clang-tidy patches I see the pre-merge checks also failed for other reasons, so it could be that this has been happening since quite a while...

**Comment by salman-javed-nz** [comment]
I'm getting this build failure on my patch too.
https://reviews.llvm.org/D108560
https://buildkite.com/llvm-project/premerge-checks/builds/57910#617b36a1-e6e3-44d2-9fc4-3f7bac037aae
Build script fails on call to `ninja check-clang-tools check-libc`.

Wasn't a problem a week or so ago, when the build script called `ninja all; ninja check-all`:
https://buildkite.com/llvm-project/premerge-checks/builds/56918#79ba6045-bf3f-4b0d-b0b0-a4c292cfba96

**Comment by joker-eph** [comment]
Right, it is only on windows that the check-libc target isn’t defined, but I can’t figure out why.
I sent an email to libc-dev@ but it is in the moderation queue right now

**Comment by salman-javed-nz** [comment]
I am not an expert in the build infrastructure, nor libc, but this line in `llvm/projects/CMakeLists.txt` looked interesting to me:
https://github.com/llvm/llvm-project/blob/5e147d3058a0a01c19c83d322bef50bdaf8873ee/llvm/projects/CMakeLists.txt#L29
```CMake
if(${LLVM_BUILD_RUNTIME})
  # MSVC isn't quite working with libc++ yet, disable it until issues are
  # fixed.
  # FIXME: LLVM_FORCE_BUILD_RUNTIME is currently used by libc++ to force
  # enable the in-tree build when targeting clang-cl.
  if(NOT MSVC OR LLVM_FORCE_BUILD_RUNTIME)
    # Add the projects in reverse order of their dependencies so that the
    # dependent projects can see the target names of their dependencies.
    add_llvm_external_project(libunwind)
    add_llvm_external_project(pstl)
    add_llvm_external_project(libc)
```

**Comment by joker-eph** [comment]
Thanks!

We likely should just disable Windows testing for libc as well then: #354
