### ISSUE TITLE
Server errors from pre-merge checks

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/llvm-premerge-checks#369]
It looks like the pre-merge checks have started returning internal server errors and nginx bad gateway. I think this is an issue with phab, not buildkite (@joker-eph FYI). Some examples:

- https://reviews.llvm.org/harbormaster/build/203402/
- https://reviews.llvm.org/harbormaster/build/203404/
- https://reviews.llvm.org/harbormaster/build/203400/
- https://reviews.llvm.org/harbormaster/build/203397/

**Comment by GMNGeoffrey** [comment]
Wait I take back my diagnoses. It looks like buildkite is down. I'm getting 502 responses from the website as well

**Comment by keith** [comment]
https://www.buildkitestatus.com/incidents/5xlht1w0p780

**Comment by metaflow** [comment]
yes, looks like it was a buildkite failure
