### ISSUE TITLE
Global post-checkout hook is sluggish on Windows

### ISSUE THREAD

**Issue by mstorsjo** [google/llvm-premerge-checks#375]
The Global post-checkout hook stage, which essentially runs `git gc`, takes a significant amount of time (at least in the case of the libcxx CI). E.g. in https://buildkite.com/llvm-project/libcxx-ci/builds/7378, the Windows build jobs (the Clang-cl and MinGW jobs) spent 4,5-6 minutes each in that stage - which is a pretty sigificant portion of the total runtime of the jobs.

I guess one can't omit this step as it's probably quite essential, but would it be better to only run it every N checkouts, instead of every time?

**Comment by metaflow** [comment]
@mstorsjo yes, we should run this step as otherwise there is a possibility to consume all disk space. I will probably make it probabilistic rather than "every N" to avoid keeping a state.
Thank you for reporting!

**Comment by mstorsjo** [comment]
Yeah... I wonder why it takes such a long time compared to the couple seconds runtime on Linux - but I presume it's a known issue/limitation with Windows filesystems and/or layers in the stack (docker/windows containers?) used here, so probably not worth making a fuss about further upstream.
