### ISSUE TITLE
Presubmit on debian seems to run out of space

### ISSUE THREAD

**Issue by ftynse** [google/llvm-premerge-checks#379]
```
OSError: [Errno 28] No space left on device
```

See https://buildkite.com/llvm-project/premerge-checks/builds/74319#d6905bb0-0606-431b-ac5b-91571193e604, https://buildkite.com/llvm-project/premerge-checks/builds/74350#bca83e4e-aaa9-42bc-ade3-868d99a7140f for example.

**Comment by metaflow** [comment]
HI Alex! @ftynse I will take a look.

**Comment by metaflow** [comment]
I have restarted the deployement as a quick relief but not sure what caused it. Disk usage of this agent was 70GiB while machines have 200GiB available. Will look on configuration closer later.

**Comment by ChristianKuehnel** [comment]
If I remember correctly, we did not mount a  volume for the working
directory in our kubernetes deployment and so kubernetes limits the amount
of space we can allocate to some fixed number. Iirc we would have to use a
tmpfs.l to get beyond the limit.

I'll take a look today, if that's the case.

--
Best,
Christian

Mikhail Goncharov ***@***.***> schrieb am Di., 18. Jan. 2022,
21:12:

**Comment by ChristianKuehnel** [comment]
Yes, we don't have a volume mounted for our working directory, but should have an `emptyDir` mount:
https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

I'll propose a patch after my next meeting

**Comment by metaflow** [comment]
We should be good now but it also might be masked by simple fact of restarting VMs. Let's reopen / create a new bug if this reappears.

**Comment by ChristianKuehnel** [comment]
We should now see the disc usage on the Google Cloud dashboards. IIRC the disk usage is only counted for mounted volumes (and not for stuff in other paths):
![Screenshot 2022-01-20 at 11 36 20](https://user-images.githubusercontent.com/19961352/150322709-e2d1e642-c6af-4e5d-8a5f-9f3a708bac21.png)
