### ISSUE TITLE
cleanup branches workflow started to fail

### ISSUE THREAD

**Issue by metaflow** [google/llvm-premerge-checks#381]
I have noticed that "clenaup branches" workflowflow never completes as it stuck on some interactive questions. Moreover it's never times out so it had occupied all agents.

**Comment by ChristianKuehnel** [comment]
Looks like the problem is a change of the SSH host key on GitHub. So we
need to update the key locally.

https://buildkite.com/llvm-project/cleanup-branches/builds/590#9a7b3321-ecc7-4ae6-8d14-ac18f6b45130

--
Best,
Christian

Mikhail Goncharov ***@***.***> schrieb am Mi., 26. Jan. 2022,
19:03:

**Comment by metaflow** [comment]
I have:
1. documented how to update ssh keys (apparently ed25519 is a current recommendation) and updated secret. Some agents are to be restarted but I am postponing it until I confirm that bolt configuration runs fine. 
2. updated "cleanup" pipeline to run on "service" queue and also added timeout of 10 minutes.
Recent successful run: https://buildkite.com/llvm-project/cleanup-branches/builds/602
