### ISSUE TITLE
Release build triggers libc++ pipeline on a wrong commit

### ISSUE THREAD

**Issue by metaflow** [google/llvm-premerge-checks#389]
https://buildkite.com/llvm-project/llvm-releases/builds/1358 on llvm 14.x branch has triggered libcxx pipeline on completely unrelated commit.

**Comment by ldionne** [comment]
Gentle ping on this, I have no idea what's going on but it's creating a lot of traffic on the libc++ pipeline :(

**Comment by metaflow** [comment]
Hi Louis! Yea, I remember! will try to look at that tomorrow. sorry for the
delay.

**Comment by metaflow** [comment]
@ldionne I think I have fixed it. Sample build https://buildkite.com/llvm-project/llvm-releases/builds/1416 .

**Comment by ldionne** [comment]
@metaflow Yes, this is fixed now indeed. Thank you so much for taking a look, BuildKite is a lot more usable now! I really appreciate the support -- I had to cancel old jobs every day previously 😅
