### ISSUE TITLE
Build LLD for BOLT testing

### ISSUE THREAD

**Issue by aaupov** [google/llvm-premerge-checks#401]
Can we please turn on `lld` subproject for BOLT build/test? 
It looks like an upstream diff https://reviews.llvm.org/D126747 triggers a bug in system lld (I think it's lld-12) and pre-merge checks fail. (@maksfb can provide more details about it if needed.) The issue can be avoided if we use trunk lld built along with BOLT.

**Comment by aaupov** [comment]
Hi @metaflow! Thank you for adding LLD as BOLT dependency.

We would also need to remove BOLT_LLD_EXE from here: 
https://github.com/google/llvm-premerge-checks/blob/main/scripts/run_cmake_config.yaml#L31
(BOLT_LLD_EXE overrides just-built lld)
Thanks!

**Comment by aaupov** [comment]
Ping @metaflow

**Comment by metaflow** [comment]
done! Sorry I am on vacation and don't check my mail 🌴

**Comment by aaupov** [comment]
Thanks a lot! It worked on that problematic diff. 
Sorry about bugging you on a vacation. Have a great rest of your time off!
