### ISSUE TITLE
Please add libc++ and lldb to the precommit CI pipeline for Clang

### ISSUE THREAD

**Issue by AaronBallman** [google/llvm-premerge-checks#409]
Changes to Clang can have cascading effects on other projects like libc++ and lldb, so knowing that a patch is going to break one of the projects relying on Clang's behavior in advance of committing the changes would reduce quite a bit of disruption. As an example: https://reviews.llvm.org/D129048 was just reverted on effectively no notification, which is an unfortunate experience given that the author of the change is a GSoC participant and this was their introduction to the community. Getting notification in precommit CI would have been incredibly useful in showing him the value of having precommit CI as well as avoiding the revert.

**Comment by mizvekov** [comment]
Happened exactly the same thing to me on this MR / commit as well: https://reviews.llvm.org/D112374

A big patch with a lot of test churn got reverted, which is time consuming to maintain out of tree.

I got no prior notification, the project affected (lldb) does no pre-commit testing, and I have been spending a lot of time trying to even get the project to build correctly and run that test on my machine.

That project requires many dependencies and the build system setup is quite fragile... I completely agree it's unreasonable.

Reading the logs from the bot test failure, I would say I am 99% confident the test expectation change required is identical to many others in the commit.

**Comment by metaflow** [comment]
Thank you for the report! Looking on dependency setup: we already have a logic to run tests on all affected projects. The only issue is that lldb was excluded from being executed as it have been constantly failing or flaking. Do you know if situation has improved?

**Comment by AaronBallman** [comment]
> Do you know if situation has improved?

I honestly have no idea regarding lldb. I know I've seen at least one test of theirs that's been flakey (from watching bots in IRC), but I would argue that such tests should be disabled regardless (if the test is so unstable we consider not adding the entire test suite to precommit CI, it's a low value test).

**Comment by mordante** [comment]
Is there an update on this request. I would love Clang to test libc++ since we had some Clang changes affecting libc++ recently. Do you need assistance to setup testing libc++ with Clang?

**Comment by ldionne** [comment]
This was done in https://reviews.llvm.org/D137759, but we would really like to move from our own libc++ runners to Clang-dedicated runners. @metaflow how do you get your clang-dedicated runners? Could we get some with a specific Docker image installed on them?

**Comment by metaflow** [comment]
yes, we use a docker image containers/agent-builkite-debian. I have not updated them in a while..

**Comment by metaflow** [comment]
@ldionne after re-reading comments I think I misunderstood you. Do you want to run a new set of agents with a different setup?

**Comment by metaflow** [comment]
why it's not possible to use the same setup for "normal" linux and libc++?

**Comment by metaflow** [comment]
as I reading initial post - Aaron is asking to start lldb / libc++ pipelines when clang is updated. This is possible to configure.

**Comment by AaronBallman** [comment]
> as I reading initial post - Aaron is asking to start lldb / libc++ pipelines when clang is updated. 

That's correct @metaflow -- my goal is to alert folks working on Clang when we've made a change that impacts libc++ or lldb before the author commits the patch.

**Comment by metaflow** [comment]
I *think* that's what you need :arrow_up:  - now when clang is touched libcxx /  libcxxabi projects will also be checked. That does not touch libcxx runners

**Comment by AaronBallman** [comment]
Thank you! Is it possible to also do lldb as well?

Also, is the FIXME comment still accurate there? (`# FIXME: not sure about 'libcxx' and 'libcxxabi'`)

**Comment by metaflow** [comment]
added lldb and removed fixme

**Comment by AaronBallman** [comment]
Thank you!
