### ISSUE TITLE
libc++ CI being skipped (randomly?) but Phabricator reports a success

### ISSUE THREAD

**Issue by ldionne** [google/llvm-premerge-checks#445]
I am forking this issue off of #438 since it's different.

https://llvm.org/D143914 used to show the build results as passing, when in reality https://buildkite.com/llvm-project/libcxx-ci/builds/22675 was skipped. We can't see that the build results are passing on D143914 anymore because it got closed, but it was that way before we closed it.

_Originally posted by @ldionne in https://github.com/google/llvm-premerge-checks/issues/438#issuecomment-1517880143_

**Comment by metaflow** [comment]
it was not skipped randomly: https://buildkite.com/llvm-project/diff-checks/builds/166609#0187a3da-cb41-4dde-9449-fef46cd5835e 

if there is another build triggered for the same diff we cancel the previous one as not interesting. I believe we specifically added this feature, maybe even with you.

I have updated the report and now it will report failure back to Phabricator, I assume that the next "new" build will update status on phabricator correctly.

**Comment by ldionne** [comment]
> if there is another build triggered for the same diff we cancel the previous one as not interesting. I believe we specifically added this feature, maybe even with you.

Yes, I know that and I remember, but in the case I am referring to, there was no other build started after the one that got skipped. Is it possible that what happened is that we would update the patch, a new job would fail to be created, but we'd still cancel the previous one? Then the cancelled job would finish (as a success because we just skip the libcxx pipeline) and we'd report that to Phabricator, which is basically a confusing result.

**Comment by metaflow** [comment]
I think that the job got cancelled based on branch name - so we should have
executed the diff application. as a disclaimer - I have not tested the
updated code in skip scenario and would appreciate if you tell if it is
still broken or not

**Comment by ldionne** [comment]
Is that deployed yet?

**Comment by metaflow** [comment]
aha

**Comment by ldionne** [comment]
Ah, I see it's live indeed. From https://reviews.llvm.org/D138680:

<img width="2640" alt="Screenshot 2023-05-04 at 5 51 12 PM" src="https://user-images.githubusercontent.com/700834/236337730-57f8052c-73b7-4bd3-b35a-2418254b0ed4.png">

The new implementation surfaces all the jobs in the Phabricator UI, including those that didn't run (e.g. because a previous step failed). This is a bit unwieldy -- would it be difficult to have a single link to the libcxx pipeline instead? There all the jobs are already presented in an aggregated form.

**Comment by metaflow** [comment]
right that's too spammy, I will update this tomorrow.

**Comment by metaflow** [comment]
updated, now it will only tell about "libcxx CI FAILED"

**Comment by metaflow** [comment]
@ldionne is it better now?

**Comment by ldionne** [comment]
Yes, this is much better now, we can just click on the link and it takes us to the build, which is great. Thanks!
