### ISSUE TITLE
[libcxx] Generated Output step of libcxx fails on premerge checks

### ISSUE THREAD

**Issue by chaitanyav** [google/llvm-premerge-checks#448]
Link to the relevant log files 

https://buildkite.com/llvm-project/libcxx-ci/builds/24566#01883c86-f0f3-4710-912a-581cf04753ff
https://buildkite.com/llvm-project/libcxx-ci/builds/24593#018840c7-9618-40aa-9a80-05c763fc6163

**Comment by metaflow** [comment]
cc @mstorsjo @ldionne

**Comment by ldionne** [comment]
This has been fixed now, it was an issue with our libc++ ci infrastructure.
