### ISSUE TITLE
Investigate llvm/test/tools/llvm-ar/mri-utf8.test

### ISSUE THREAD

**Issue by sam-mccall** [google/llvm-premerge-checks#47]
The premerge check (always) claims this test is failing.
However it passes locally for me, and AFAICS on all the buildbots.
So there may be something odd about the configuration of the premerge check workers (or maybe this is a real test failure in a valid though untested configuration and the test/code needs to be fixed)

**Comment by sam-mccall** [comment]
Oops, the detailed logs *are* available...

```
: 'RUN: at line 23';   env LANG=en_US.UTF-8 "/usr/bin/python" -c "assert open(u'\U000000A3.txt', 'rb').read() == b'contents\n'"
--
Exit Code: 1

Command Output (stderr):
--
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3' in position 0: ordinal not in range(128)
```

My read is that the `python` on this machine is trying to convert the path argument to ASCII.
On my machine, I get the same error when replacing `en_US.UTF-8` with `en_US.ASCII`, so maybe the utf8 locale isn't installed?

If this is something debianish, apparently the required package is `locales`.

**Comment by ChristianKuehnel** [comment]
yep was a problem with the locale. Setting that in the docker container solved it.

Build with successful tests:
https://results.llvm-merge-guard.org/amd64_debian-testing_clang-8_check-all-411/
