### ISSUE TITLE
strip down git clone operation

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#49]
* git clone --depth 1
* git fetch <parent hash-id from diff>
* cache the git repo on the builder

**Comment by davezarzycki** [comment]
Is caching the repo not an option on the builders?

**Comment by ChristianKuehnel** [comment]
Yes it is. I added it above.

**Comment by ChristianKuehnel** [comment]
performance on Jenkins and buildkite is good enough right now --> closing this issue
