### ISSUE TITLE
Sign up for public beta testing

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#54]
I you are interested in paricipating in the beta tests for the pre-merge checks:
Leave a comment on this issue with your **Phabricator user name**. We will then add you.

For the Phabricator integration and bug reports, please see the [user documentation](https://github.com/google/llvm-premerge-checks/blob/master/docs/user_doc.md).

**Comment by JDevlieghere** [comment]
`jdevlieghere`

**Comment by joker-eph** [comment]
I'm up :) 
joker-eph

**Comment by joker-eph** [comment]
Actually it may be more convenient if we could just send you a pull-request to get added to the whitelist?

**Comment by ChristianKuehnel** [comment]
Done.

@joker-eph your account on phabricator is "disabled", so I used your other account `m...` instead.

But good point: the signup is a bit clumsy. I'll change it to being a member of this project: https://reviews.llvm.org/project/members/78/ There users can self-register. I already registered the two of you there. I'll also update the documentation in #58.
