### ISSUE TITLE
Add lldb (and others) to enabled projects list

### ISSUE THREAD

**Issue by rupprecht** [google/llvm-premerge-checks#55]
Background info:
Patch: https://reviews.llvm.org/D70137
Config: https://results.llvm-merge-guard.org/amd64_debian_testing_clang8-72/CMakeCache.txt
Full log: https://results.llvm-merge-guard.org/amd64_debian_testing_clang8-72/console-log.txt

The merge guard bot seems to have run successfully. However, my patch was for lldb, and it didn't run any lldb tests, probably because the cmake config `LLVM_ENABLE_PROJECTS:STRING=clang;clang-tools-extra;libcxx;libcxxabi;lld;libunwind` doesn't include it.

Would it be possible to set `LLVM_ENABLE_PROJECTS:STRING=all` instead?

**Comment by ChristianKuehnel** [comment]
Yes, of course this is possible. Let me run a test to see the performance impact.

**Comment by ChristianKuehnel** [comment]
#113 is rolled out to all beta testers: Projects affected by a change are detected automatically and only those are built and tested. lldb changes should now be covered on Linux. 

I had to disable quite a few projects on Windows as the builds kept failing, including lldb.
