### ISSUE TITLE
The bot attempts and fails to apply dependencies which have already landed

### ISSUE THREAD

**Issue by pcc** [google/llvm-premerge-checks#72]
The pre-commit check initially succeeded on my change https://reviews.llvm.org/D71081 but started failing after two of its dependencies https://reviews.llvm.org/D71077 and https://reviews.llvm.org/D71078 landed. Looking at console-log.txt I see:
```
running arc patch...
 INFO  Base commit is not in local repository; trying to fetch.

 Patch Failed! 
Checking patch compiler-rt/lib/scudo/standalone/tests/wrappers_c_test.cpp...
error: while searching for:
int malloc_iterate(uintptr_t base, size_t size,
                   void (*callback)(uintptr_t base, size_t size, void *arg),
                   void *arg);
}

// Note that every C allocation function in the test binary will be fulfilled

error: patch failed: compiler-rt/lib/scudo/standalone/tests/wrappers_c_test.cpp:20
Applying patch compiler-rt/lib/scudo/standalone/tests/wrappers_c_test.cpp with 1 reject...
Rejected hunk #1.
Usage Exception: Unable to apply patch!
```
So it looks like it was trying to apply D71077 but it failed because the patch had already been applied when the change landed.

Maybe the bot should ignore dependencies that have been closed?

**Comment by ChristianKuehnel** [comment]
Thank you for looking into the issue. I've already seen quite a few failures related to `arc patch`. 

The bot just calls `arc patch` to identify and apply the patches on top of the git repository. And it seems that `arc patch` does not detect that some of the dependent patches have already landed. 

To address this issue, I see several options:
1. We ask the maintainers of `arc` to look into this.
1. We write our own `arc patch` clone and implement the logic there. I suppose we can get the patches from Phabricator via the conduit API and then decide which ones to apply.
1. We switch Phabricator to use a [staging area](https://secure.phabricator.com/book/phabricator/article/harbormaster/). Then the build server will not only check  the patch, but the entire state of your local working copy. This will come with some additional maintenance effort for the staging area and will impact the developers' workflows. The staging area solution will however not detect issues if your working is in some weird state or if the patch cannot be applied to master later.
1. We switch to GitHub pull requests, there you always submit a patch with a valid git history. From a CI system perspective, this is the best solution, but it comes with major changes to the development workflow...

What do you think?

**Comment by pcc** [comment]
I would probably go for 2.

Actually downloading the patch isn't that hard, I have a quick one-liner shell script to do it:
```
#!/bin/sh

wget -O "/tmp/$1.diff" "https://reviews.llvm.org/$1?download=true"
```
I imagine that all we'd need on top of that would be to figure out which conduit calls to use to figure out the dependencies and which ones are closed.

I don't entirely understand the concept of the staging area in Phabricator, but in my opinion we should test patches as close to master as possible (rather than the revision used in the working copy), as this gives us the state that is closest to what will actually be committed.

**Comment by ChristianKuehnel** [comment]
I gave option 2. a shot. It was more complicated than exceted as we need to traverse the object model of Phabricator to get the relevant information.

So this probably needs more testing before releasing it.

**Comment by joker-eph** [comment]
An alternative way of patch a sequence of dependent revision: https://github.com/mozilla-conduit/review

(didn't try it but was mentioned on llvm-dev)

**Comment by ChristianKuehnel** [comment]
The `apply_patch2.py` script is now live in the Windows builds (not user visible yet). Let's see how that performs. If that works nicely, we'll also use it for the Linux builds.

**Comment by ChristianKuehnel** [comment]
apply_patch2.py also used for LInux. Should fix these issues
