### ISSUE TITLE
Switch host compiler version

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#76]
Based on the request in #75 

@joker-eph I was simply using the latest clang version Debian testing has to offer: https://packages.debian.org/bullseye/clang

Which one would you recommend instead?
Version 9 from http://apt.llvm.org/?

What would be the rationale for picking the host compiler? 
Always use the latest clang release?

**Comment by joker-eph** [comment]
I don't have a strong rational to offer here, not sure about the pros/cons :)

**Comment by njames93** [comment]
I know this is old and closed but shouldn't we be using the minimum version llvm states it supports (clang 3.5)

**Comment by ChristianKuehnel** [comment]
Our rationale was: The pre-merge tests sound find problems that block other developers and our assumption was that LLVM developers are using a rather fresh version of the tools.

What would be the rationale for the old one?

**Comment by joker-eph** [comment]
A rational would be that we want to detect if someone if landing a change with a feature not supported, and building with an old compiler is a good way to figure it out.

**Comment by njames93** [comment]
> A rational would be that we want to detect if someone if landing a change with a feature not supported, and building with an old compiler is a safer testing.

Precisely that. If we give users the option to build llvm from source and they are using an old host compiler(maybe their distro default) but its listed as supported they should be able to build llvm with it. Should a developer try to land a patch that will break on an old but supported version we should block it (or have a long hard discussion about increasing the minimum supported version.)
