### ISSUE TITLE
Failures if patch committed too fast...

### ISSUE THREAD

**Issue by echristo** [google/llvm-premerge-checks#79]
In https://reviews.llvm.org/D71395 I got approval and committed before the test infrastructure was able to build and instead of recognizing that the patch was committed already it failed trying to apply the patch and errored out.

Perhaps we could add some code to notice?

**Comment by ChristianKuehnel** [comment]
The link you provided has a passing build, did you link the right one?

Beyond that: I think this is a duplicate of #72.

**Comment by echristo** [comment]
It initially failed :)

Harbormaster failed remote builds in B42366: Diff 233518!Wed, Dec 11, 11:57 PM
Harbormaster completed remote builds in B42364: Diff 233514.

That said, perhaps #72 is the right one to use here.
