### ISSUE TITLE
clang-format/tidy gives invalid suggestions for the clang/test directory

### ISSUE THREAD

**Issue by mordante** [google/llvm-premerge-checks#89]
**Describe the bug**
While letting the bot run on my patch https://reviews.llvm.org/D71966 it suggests that I should apply the following formatting patch 
http://results.llvm-merge-guard.org/amd64_debian_testing_clang8-693/clang-format.patch

Applying the patch would break the unit tests. Especially `clang/test/Index/comment-to-html-xml-conversion.cpp` does create these long lines and they should not be formatted.

it also suggests code fixes
https://results.llvm-merge-guard.org/amd64_debian_testing_clang8-693/clang-tidy.txt

Fixing them may be useful for these tests, but there are a lot of tests that will generate warnings since they test compiler warnings.

**To Reproduce**
1. Run the bot for this https://reviews.llvm.org/D71966

**Expected behavior**
I expect the `clang/test` directory to be excluded from clang-format/tidy. Probably the same for other `test` directories in the project.

Note the build failure is on me.

**Comment by ChristianKuehnel** [comment]
@metaflow can you please take a look?

**Comment by metaflow** [comment]
Looking into that.

**Comment by metaflow** [comment]
#101 fixed clang-format settings. It will not try to split long lines anymore

**Comment by metaflow** [comment]
#102 will ignore /test path.

**Comment by mordante** [comment]
Thanks for looking into the issue.

Unfortunately it seems the clang-format fixes do not work properly
https://reviews.llvm.org/D73434
It still warns about the formatting of files in clang/test subdirectory.
I see no clang-tidy warnings :-)

**Comment by njames93** [comment]
I think the fix was to not run clang tidy on test directories, but run clang-format using the .clang-format file found in the directory tree
