### ISSUE TITLE
clang-tidy suggests changes to lldb for a patch that only touches llvm

### ISSUE THREAD

**Issue by jayfoad** [google/llvm-premerge-checks#90]
For this patch, which only touches llvm: https://reviews.llvm.org/D72392
clang-tidy makes these suggestions in lldb: https://results.llvm-merge-guard.org/amd64_debian_testing_clang8-955/clang-tidy.txt
These suggestions seem completely irrelevant to my patch.

**Comment by ChristianKuehnel** [comment]
@metaflow can you please take a look?

**Comment by metaflow** [comment]
looking into that

**Comment by metaflow** [comment]
I have tried this patch with recent changes and it seems fine.
