### ISSUE TITLE
Suggesting fixes for test files that dont appear in CompileCommands

### ISSUE THREAD

**Issue by njames93** [google/llvm-premerge-checks#92]
I have a test case file for a clang-tidy check that obviously doesn't get compiled when building. However ClangFormat is suggesting all the long // CHECK-MESSAGES: lines get folded to below 80 characters which would in turn break the FileCheck.

Results in patch lines like this 
`-  // CHECK-MESSAGES-NOT: [[@LINE-1]]:{{\d*}}: warning: Use Pre-increment instead of Post-increment
-  // CHECK-FIXES-NOT: {{^}}  ++It;
+  // CHECK-MESSAGES-NOT: [[@LINE-1]]:{{\d*}}: warning: Use Pre-increment instead
+  // of Post-increment CHECK-FIXES-NOT: {{^}}  ++It;`

Case which this appears on: https://reviews.llvm.org/D72553

Proposed solution only run lint and format checks on files that actually need to be built (aka that appear in a compile database)

**Comment by ChristianKuehnel** [comment]
@metaflow can you please take a look?

**Comment by zorg93** [comment]
I have just realised, the test directories have a .clang-format file that specifies the column limit is 0, but this isn't reading the .clang-format file and blindly using a limit of 80 lines

**Comment by metaflow** [comment]
Yes, I think your are right Nathan. I am checking now if removing `--style` completely will solve the issue.

**Comment by metaflow** [comment]
clang-format should now obey `.clang-format`

**Comment by njames93** [comment]
Tested it on a patch I submitted and it worked perfectly. I still think once we get clang-tidy up and running again it should be wise to only run on files that need compiling instead of test files
