### ISSUE TITLE
merge_guards_bot reports clang-tidy/clang-format findings unrelated to modified code

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#94]
Look into the issues/proposals in this thread on the mailing list:
* http://lists.llvm.org/pipermail/llvm-dev/2020-January/137899.html
* http://lists.llvm.org/pipermail/llvm-dev/2020-January/137918.html

**Comment by metaflow** [comment]
> http://lists.llvm.org/pipermail/llvm-dev/2020-January/137899.html

that were errors for file in `clang/test`, addressed by #102

**Comment by metaflow** [comment]
> http://lists.llvm.org/pipermail/llvm-dev/2020-January/137918.html

clang-format issue is fixed already in #92
