### ISSUE TITLE
upgrade linux docker image to LLVM 9.0.1

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#95]
We should probably use the latest version of our own tools, so we should upgrade the docker container to use the latest LLVM release: 9.0.1

Debian packages are available on http://apt.llvm.org/
Please use @ChristianKuehnel's "Automatic installation script" so that we see it's actually working ;)

**Comment by metaflow** [comment]
What do you think about using 10th? It should be stable enough now
