### ISSUE TITLE
Exclude lint test files from clang-format

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#98]
from: https://reviews.llvm.org/D72715

Maybe also check if there are other file types that should be excluded...

**Comment by kadircet** [comment]
Yeah actually I had also reported this to @metaflow last week (should've filed it here instead I suppose).

There is actually a .clang-format file inside clang/test/ directory, but for some reason the clang-format being run during the premerge builds doesn't pick that up, hence the false positives.

**Comment by njames93** [comment]
This seems to be the same issue as #92

**Comment by ChristianKuehnel** [comment]
@njames93 yes, thx. Close this ticket as duplicate.
